# Generated by Django 4.0.4 on 2022-06-04 15:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('BlogLeyes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themes',
            name='id',
            field=models.CharField(default=uuid.UUID('d18e6c53-7806-47b5-96db-b37187b155eb'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='topics',
            name='id',
            field=models.CharField(default=uuid.UUID('21af6e1c-bb51-444d-a267-32109cce7efe'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='writer',
            name='id',
            field=models.CharField(default=uuid.UUID('ccdaeed5-fdd9-49bb-96c8-a21b69b5b145'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('cuerpo', models.CharField(max_length=1000)),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BlogLeyes.writer')),
            ],
        ),
    ]
