# Generated by Django 4.0.4 on 2022-07-04 20:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('BlogLeyes', '0002_alter_themes_id_alter_topics_id_alter_writer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='writer',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='themes',
            name='id',
            field=models.CharField(default=uuid.UUID('598269e9-55d8-4d3c-be7d-6e313c25ed0d'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='topics',
            name='id',
            field=models.CharField(default=uuid.UUID('ddc4e1cd-0874-4020-a5ef-5dded54471c0'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='writer',
            name='id',
            field=models.CharField(default=uuid.UUID('211187b4-d92e-4016-82d5-ae453a51bcae'), max_length=100, primary_key=True, serialize=False),
        ),
    ]
