# Generated by Django 4.0.4 on 2022-07-05 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BlogLeyes', '0003_alter_articulo_writer_alter_themes_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themes',
            name='id',
            field=models.CharField(default=uuid.UUID('8efaa8e4-6b9f-4775-a52c-a46bfff3f592'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='topics',
            name='id',
            field=models.CharField(default=uuid.UUID('701af796-824f-4d66-8c4f-f2102fd0aefe'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='writer',
            name='id',
            field=models.CharField(default=uuid.UUID('fb3add84-deed-437e-b3dd-adcd50324c3d'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
