# Generated by Django 4.0.4 on 2022-07-05 22:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('BlogLeyes', '0004_alter_themes_id_alter_topics_id_alter_writer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themes',
            name='id',
            field=models.CharField(default=uuid.UUID('24af5461-de55-4e51-a594-4cfcd5b633fe'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='topics',
            name='id',
            field=models.CharField(default=uuid.UUID('048075ef-bcdc-4357-b6bd-96ef893f3048'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='writer',
            name='id',
            field=models.CharField(default=uuid.UUID('21a0895c-4d7b-4ac6-84e8-6f72898ca5a5'), max_length=100, primary_key=True, serialize=False),
        ),
    ]
